### PR TITLE
feat(modeler): introduce drag-drop-images and top-modal modules

### PR DESCRIPTION
**Pull request by xanpj**
I implemented a drag and drop feature for multiple images upload. Also, I introduced a general top modal module for action feedback. This is crucial for the drag drop feature, in order to get tangible ui feedback.

There might be some merging necessary when the image-selection PR (https://github.com/pinussilvestrus/postit-js/pull/23) gets through, as i updated some util function to allow to work properly for multi-file upload. But nothing difficult.

Screen Shot 2020-06-09 at 9 39 42 PM

Screen Shot 2020-06-09 at 9 37 27 PM

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
@xanpj I thought about this pull request and maybe shipping this one to an extension could be a better option? I really want to keep the core as clean as possible and not overload it with so much extra stuff which would blow it up. 

Which means to not include it inside the core of `postit-js` but offering it as an extension / plug-in which one can simply include inside the Modeler. We could than reference this to this core project and also include it in the demo.

We could do that via
* an own extension repository, like [`diagram-js-minimap`](https://github.com/bpmn-io/diagram-js-minimap)
* handling supported extension inside this repo by introducing a multi-package-project, e.g. with [lerna](https://github.com/lerna/lerna)
  * `packages`
    * `core`
    * `example`
    * `drag-drop-extension`
    * .....

What do you think about that? Is it reasonable to you?

**Comment by xanpj** [comment]
Let's do it as an extension. What should we do with the modal. Include it in the core our do another extension that would be required by the drag-drop module?

**Comment by pinussilvestrus** [comment]
Can you quickly explain what the Modal component is about? A General Modal component, which also the image selection could use?

For the extension: feel free to create a project for that like the minimap-extension, which we can mention here in the Readme (maybe with an "Extensions" section and ask, if you need Help. 

Once we have this and clarified what to do with the modals, we can close this one here :+1:

**Comment by xanpj** [comment]
The top modal is the the green bar in the top of the second image saying "2 files uploaded". That is not a native module.

If remember seeing a native modal in diagram.js or bpmn.js but can't remember where. Can you point me to it? Maybe we could use that one instead then.

**Comment by pinussilvestrus** [comment]
I think we're save to use the [Tooltips module](https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/tooltips/Tooltips.js) 👍

**Comment by xanpj** [comment]
I have uploaded the drag-drop feature as a module in https://github.com/xanpj/postit-js-extensions

**Pull request closed without merging**
