### PR TITLE
feat(example): add postit-js-extensions to demo

### PR DESCRIPTION
**Pull request by xanpj**
Added extensions to demo. Created dependency only for the **example** project to 
[postit-js-extensions](https://github.com/xanpj/postit-js-extensions)

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Cool! I'm curious, how to use the organizing feature? I can't see a button.

Also when dropping images. The image itself got created on the board, but there is no visual indicator for me. 

Kapture 2020-06-19 at 16 09 58

Anything which has to be added to the demo?

**Comment by xanpj** [comment]
If you select a group and at least one other element, the button dynamically appears. The grouping only works if the element is inside the group through.

I removed the modal. The native tooltip wasn’t what I was looking for. Might do it in another module and include it.

**Comment by pinussilvestrus** [comment]
That's pretty cool!

**Comment by pinussilvestrus** [comment]
Just for a possible improvement of the organizing feature: maybe the button could be disabled if not available and get active once the requirements are filled. Therefore the user would see in the first place, there is something and the feature is more discoverable. Also, the button could have a small tooltip to describe how to use the feature 💡

**Comment by xanpj** [comment]
> Just for a possible improvement of the organizing feature: maybe the button could be disabled if not available and get active once the requirements are filled. Therefore the user would see in the first place, there is something and the feature is more discoverable. 💡

Hints have been added for the SelectionOrganizer and DragDropImages extensions.

**Pull request merged**
